"""Init tariffs

Revision ID: 77a839cc836c
Revises: 
Create Date: 2026-04-30 15:12:50.112503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a839cc836c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_rules_id'), 'tariff_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_rules_id'), table_name='tariff_rules')
    op.drop_table('tariff_rules')
    # ### end Alembic commands ###
